openapi: 3.0.3
info:
  title: Minimal Bearer Auth API
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /user/profile:
    get:
      summary: Get user profile
      description: Retrieve profile information for the authenticated user.
      responses:
        '204':
          description: Successful response
